version: '2'
services:
  jenkins:
    container_name: "jenkins-dood"
    build:
      context: ./
      args:
        - DOCKER_GROUP_ID_HOST=${DOCKER_GROUP_ID}
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
    ports:
      - 8080:8080
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # mount docker.sock on host
